os: linux
language: c
dist: bionic

addons:
  homebrew:
    packages:
    - help2man
    - flex
    - texinfo
    update: true
  apt:
    packages: &default_deps
      - python3
      - cython3
      - flex
      - help2man
      - autopoint
      - texinfo

# env:
#   global:
#     - VERBOSE=1

jobs:
  include:
    - os: osx
      env:
        - LDFLAGS="-L/usr/local/opt/flex/lib -L/usr/local/opt/texinfo/lib"
        - CPPFLAGS="-I/usr/local/opt/flex/include"
        - PYTHON=/usr/local/bin/python3
    - os: linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install cython ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/flex/bin:/usr/local/opt/texinfo/bin:/usr/local/opt/gettext/bin:$PATH" ; fi

# Test TRAVIS_OS_NAME below because we cannot put the desired extra
# configure arguments for Linux in a variable, owing to spaces and quotes.
# We could use an array, but we cannot set an environment variable to an
# array.
script:
  - ./bootstrap
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --enable-silent-rules ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --enable-silent-rules --enable-package-suffix CFLAGS="-g3 -fsanitize=address -fsanitize=undefined" LDFLAGS="-fsanitize=address -fsanitize=undefined" TESTS_ENVIRONMENT_EXTRA="LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so PYTHONMALLOC=malloc" ; fi
  - make && make distcheck
