language: c

dist: xenial
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - python-dbg
      - cython
      - flex
      - help2man
      - autopoint
      - texinfo
      - valgrind
      - g++-5

# env:
#   global:
#     - VERBOSE=1

matrix:
  include:
    - os: linux
      env:
        - COMPILER=gcc-5
        - PYTHON=/usr/bin/python-dbg
        - DISTCHECK_CONFIGURE_FLAGS="PYTHON=/usr/bin/python-dbg"
    - os: osx
      osx_image: xcode9.2
      env:
        - LDFLAGS="-L/usr/local/opt/flex/lib -L/usr/local/opt/texinfo/lib"
        - CPPFLAGS="-I/usr/local/opt/flex/include"
    - compiler: gcc
      env:
        - COMPILER=gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [g++-6]

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python@2 flex help2man texinfo ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install cython ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/flex/bin:/usr/local/opt/texinfo/bin:/usr/local/opt/gettext/bin:$PATH" ; fi

script:
  - ./bootstrap
  - ./configure --enable-silent-rules CC=$COMPILER
  - make && make distcheck
