language: c

dist: bionic
sudo: required

addons:
  apt:
    packages: &default_deps
      - python3
      - cython3
      - flex
      - help2man
      - autopoint
      - texinfo

# env:
#   global:
#     - VERBOSE=1

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - LDFLAGS="-L/usr/local/opt/flex/lib -L/usr/local/opt/texinfo/lib"
        - CPPFLAGS="-I/usr/local/opt/flex/include"
        - PYTHON=/usr/local/bin/python3
    - compiler: gcc
      env:
        - PYTHON=/usr/bin/python3-dbg
        - CYTHON=/usr/bin/cython3
        - CONFIGURE_ARGS=(--enable-package-suffix "CFLAGS=\"-g3 -fsanitize=address -fsanitize=undefined\"" "LDFLAGS=\"-fsanitize=address -fsanitize=undefined\"" "PY_LOG_ENV=\"LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so PYTHONMALLOC=malloc\"")
        - DISTCHECK_CONFIGURE_FLAGS="PYTHON=/usr/bin/python3 CYTHON=/usr/bin/cython3"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install flex help2man texinfo ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install cython ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/flex/bin:/usr/local/opt/texinfo/bin:/usr/local/opt/gettext/bin:$PATH" ; fi

script:
  - ./bootstrap
  - ./configure --enable-silent-rules "${CONFIGURE_ARGS[@]}" $DISTCHECK_CONFIGURE_FLAGS
  - make && make distcheck
